# Generated by Django 5.0.6 on 2026-06-22 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('deadline', models.DateTimeField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReplanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('trigger_reason', models.CharField(max_length=255)),
                ('ai_reasoning', models.TextField()),
                ('was_automatic', models.BooleanField(default=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replan_logs', to='core.goal')),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('estimated_minutes', models.IntegerField()),
                ('order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done'), ('missed', 'Missed')], default='pending', max_length=20)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='core.goal')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('was_auto_rescheduled', models.BooleanField(default=False)),
                ('reschedule_reason', models.TextField(blank=True, null=True)),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.subtask')),
            ],
        ),
    ]
