# Generated by Django 5.0.6 on 2026-06-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='action_draft',
            field=models.TextField(blank=True, help_text='AI-generated template/email/code outline to start this subtask.', null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='is_crisis_active',
            field=models.BooleanField(default=False, help_text='Enables active focus mode for this subtask.'),
        ),
    ]
